### PR TITLE
cli: Add command rerun

### PR DESCRIPTION
**Pull request by vinzenz**
cli: Add command rerun

Per request this patch adds support for rerunning leapp from a certain
point. As for now it only supports the FirstBoot phase to be re-run.

In order to accomplish the re-run functionality leapp clones the context
of the last upgrade execution and removes all checkpoints and errors
from it.
Cloning means it will duplicate all the context aware data in the
database in order to allow a post mortem inspection of what has
happened.
So it will not blindly delete data but remove the errors and checkpoints
only from the cloned part of the data.

Additionally it allows to select only actors which have a certain tag
specified during the re-run. This will help users that want to re-run
their own set of actors only during the FirstBoot phase without having
to create a complicated workaround using snactor and somehow getting it
to use the data from the upgrade. This allows the actors that are re-run
to consume messages that have been generated during the upgrade before
this phase has been run.

Signed-off-by: Vinzenz Feenstra <vfeenstr@redhat.com>

### CODE REVIEW

**Comment by Rezney** [comment]
Initial testing fails with:

~~~python
[root@leapp-20210329101334 ~]# leapp upgrade --debug --reboot
Traceback (most recent call last):
  File "/usr/bin/leapp", line 9, in <module>
    load_entry_point('leapp==0.12.0', 'console_scripts', 'leapp')()
  File "/usr/lib/python2.7/site-packages/leapp/cli/__init__.py", line 18, in main
    cli.command.execute('leapp version {}'.format(VERSION))
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 105, in execute
    args.func(args)
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 127, in called
    self.target(args)
  File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 265, in upgrade
    e.store()
  File "/usr/lib/python2.7/site-packages/leapp/utils/audit/__init__.py", line 78, in store
    with get_connection(db) as connection:
  File "/usr/lib/python2.7/site-packages/leapp/utils/audit/__init__.py", line 64, in get_connection
    return create_connection(cfg.get('database', 'path'))
  File "/usr/lib/python2.7/site-packages/leapp/utils/audit/__init__.py", line 51, in create_connection
    return _initialize_database(sqlite3.connect(path))
  File "/usr/lib/python2.7/site-packages/leapp/utils/audit/__init__.py", line 29, in _initialize_database
    db.executescript(CURRENT_SCHEMA)
sqlite3.OperationalError: near "WITH": syntax error
~~~

**Comment by Rezney** [comment]
When I try to re-run the `FirstBootPhase` without any previous Leapp run I get:

```python
Traceback (most recent call last):
  File "/usr/bin/leapp", line 9, in <module>
    load_entry_point('leapp==0.12.0', 'console_scripts', 'leapp')()
  File "/usr/lib/python2.7/site-packages/leapp/cli/__init__.py", line 18, in main
    cli.command.execute('leapp version {}'.format(VERSION))
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 105, in execute
    args.func(args)
  File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 127, in called
    self.target(args)
  File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 245, in rerun
    enablerepo=[]))
  File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 301, in upgrade
    warn_if_unsupported(configuration)
  File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 144, in warn_if_unsupported
    report_unsupported(devel_vars, configuration["whitelist_experimental"])
KeyError: 'whitelist_experimental'
```

we may want to handle this more gracefully...

**Comment by vinzenz** [comment]
> When I try to re-run the `FirstBootPhase` without any previous Leapp run I get:
> 
> ```python
> Traceback (most recent call last):
>   File "/usr/bin/leapp", line 9, in <module>
>     load_entry_point('leapp==0.12.0', 'console_scripts', 'leapp')()
>   File "/usr/lib/python2.7/site-packages/leapp/cli/__init__.py", line 18, in main
>     cli.command.execute('leapp version {}'.format(VERSION))
>   File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 105, in execute
>     args.func(args)
>   File "/usr/lib/python2.7/site-packages/leapp/utils/clicmd.py", line 127, in called
>     self.target(args)
>   File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 245, in rerun
>     enablerepo=[]))
>   File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 301, in upgrade
>     warn_if_unsupported(configuration)
>   File "/usr/lib/python2.7/site-packages/leapp/cli/upgrade/__init__.py", line 144, in warn_if_unsupported
>     report_unsupported(devel_vars, configuration["whitelist_experimental"])
> KeyError: 'whitelist_experimental'
> ```
> 
> we may want to handle this more gracefully...

oh good catch. Thanks.

**Comment by Rezney** [comment]
Issuing simply `leapp rerun FirstBoot --debug` returns `ImportError: No module named pyudev` which kind of makes sense as we run with Python2.

`/root/tmp_leapp_py3/leapp3 rerun FirstBoot --debug` works fine. Will this be our guidance to run the rerun with the `tmp_leapp_py3` ?

@shaded-enmity @pirat89

**Comment by Rezney** [comment]
@vinzenz Do we plan to provide any output for the rerun command?

**Comment by mkluson** [comment]
@vinzenz could you please provide any description of the change (if you already how the solution will work), we would need it to start our analysis

**Comment by Rezney** [comment]
leapp-ci build

**Comment by mkluson** [comment]
leapp-ci build

**Comment by Rezney** [comment]
@vinzenz As discussed, please fix the issue with the verbosity and add the check for whether a particular phase was already run and this PR should be good to go. The code looks good to me.

**Comment by Rezney** [comment]
@vinzenz 

After running the rerun command the `/var/log/leapp/leapp-upgrade.log` is archived. Don't we want to just append the logs from the rerun to the original log?

**Comment by vinzenz** [comment]
> @vinzenz
> 
> After running the rerun command the `/var/log/leapp/leapp-upgrade.log` is archived. Don't we want to just append the logs from the rerun to the original log?

I know, I made it that way

@shaded-enmity WDYT?

**Comment by shaded-enmity** [comment]
I don't have a strong opinion about this, separate log has the benefit that I can't really confuse the old output with the new output. I'm assuming that the old log is still accessible?

**Comment by vinzenz** [comment]
> I don't have a strong opinion about this, separate log has the benefit that I can't really confuse the old output with the new output. I'm assuming that the old log is still accessible?

Yes, it's just being archived, not overwritten

**Comment by pirat89** [comment]
archived logs are not part of sosreports

**Review by Rezney — APPROVED** [review]

**Comment by pirat89** [comment]
leapp-ci build

**Pull request merged**
