### PR TITLE
Dialog Component - Add TextListComponent to support list of text

### PR DESCRIPTION
**Pull request by ygalblum**
Add a new Component to hold a list of strings with a minimal count
Implement a specific renderer hook
Load and dump the list from and to the answer file as a json
Add test cases for the dialog components
Add test cases for the answerstore

### CODE REVIEW

**Comment by ygalblum** [comment]
review please @oamg/developers

**Comment by PeterMocary** [comment]
Hi, thank you for your contribution @ygalblum! :rocket: 

Could you please update the description with some additional information about the reason behind the changes?

**Comment by pirat89** [comment]
@ygalblum @PeterMocary  we need to discuss this yet as the use case behind this feature is aside of the original purpose of Dialogs. Please do not do other changes until we discuss that. We are now affected by vacations so waiting for a time most of the team is back to discuss it.

Below sharing the use case behind the PR:
* An actor needs to get multiple URLs from a user. The number of URLs is not known in advance. So the point is to get all URLs that customer needs to be used for something and consumed by an actor.

The possible solution (that is nowadays more expected regarding the dialogs design) is to tell user to create a file under `/etc/leapp/files/` that will address such a problem. In this case actors can simply read the content of such a configuration file and work with it as needed.

**Comment by ygalblum** [comment]
@pirat89 thanks for the detailed comment and yes, you are correct, this was the reason for this PR.

The reason I prefer this solution over your proposal is that I think that users will prefer to provide all the information in one place instead of multiple files. Don't think only about my actor. Once this becomes a known practice, what stops the next actor from getting answers in another file?

As for the way it was implemented, i.e. JSON inside an INI file, I looked around for how arrays are implemented in INI files and this was the most common and elegant way I found.

Having said that, because of your response (in the chat) and knowing that even if this change is merged, it will take time until it gets released, I decided to go with a hybrid solution. That is, the actor uses a JSON file to get the information it needs, but it does not force a location. Instead, it uses a Text dialog to get a path or URL to get the json from.

The advantage I saw in this solution is that it allows the user to maintain this JSON file next to where the files, to which the URLs are needed to being with, are located.

**Comment by pirat89** [comment]
@ygalblum We have discussed this in the team and we agreed this is not way we want to go in future. We want to keep dialogs for purposes they were designed and do not want to extend them in this way. Also we do not want to mix multiple formats in one file - but this was just a minor fact for the decision as that part could be done differently. In this case we suggest to go the way I've proposed above - e.g.
* ask for a path to the file in the dialog
* just inhibit the upgrade and inform user to create the file on a specified path using the specified format

Closing, we are sorry about that but thanks for your time and the contribution.

**Pull request closed without merging**
