### PR TITLE
Fix broken queries on rerun

### PR DESCRIPTION
**Pull request by dkubek**
After the update to the leapp db table names, the rerun command fails. This commit fixes the issue by using the current schema.

jira: https://issues.redhat.com/browse/RHEL-40363

### CODE REVIEW

**Comment by matejmatuska** [comment]
@dkubek Please rebase to fix packit

**Review by matejmatuska — APPROVED** [review]
Tested with local builds, since packit is broken until rebase.
Without this patch (both 7to8 and 8to9):
```
[root@leapp-20240719132659 ~]# /root/tmp_leapp_py3/leapp3 rerun FirstBoot
Traceback (most recent call last):
  File "/root/tmp_leapp_py3/leapp3", line 6, in <module>
    sys.exit(leapp.cli.main())
  File "/root/tmp_leapp_py3/leapp/cli/__init__.py", line 51, in main
    cli.command.execute('leapp version {}'.format(VERSION))
  File "/root/tmp_leapp_py3/leapp/utils/clicmd.py", line 111, in execute
    args.func(args)
  File "/root/tmp_leapp_py3/leapp/utils/clicmd.py", line 133, in called
    self.target(args)
  File "/root/tmp_leapp_py3/leapp/cli/commands/rerun/__init__.py", line 46, in rerun
    clone_context(last_context, context, db)
  File "/root/tmp_leapp_py3/leapp/utils/audit/contextclone.py", line 105, in clone_context
    _dup_metadata(db=db, oldcontext=oldcontext, newcontext=newcontext)
  File "/root/tmp_leapp_py3/leapp/utils/audit/contextclone.py", line 74, in _dup_metadata
    for row in _fetch_table_for_context(db, 'metadata', oldcontext):
  File "/root/tmp_leapp_py3/leapp/utils/audit/contextclone.py", line 7, in _fetch_table_for_context
    '''.format(table=table), (context,))
sqlite3.OperationalError: no such column: context
```
With this patch (7to8):
```
root@leapp-20240719142215 ~]# /root/tmp_leapp_py3/leapp3 rerun FirstBoot

==> Processing phase `FirstBoot`
====> * satellite_upgrader
        Execute installer in the freshly booted system, to finalize Satellite configuration
====> * enable_rhsm_target_repos
        On the upgraded target system, set release and enable repositories that were used during the upgrade
====> * insights_auto_register
        Automatically registers system into Red Hat Insights
====> * network_manager_update_connections
        Update NetworkManager connections.
====> * remove_systemd_resume_service
        Remove systemd service to launch Leapp.

Debug output written to /var/log/leapp/leapp-upgrade.log

============================================================
                      REPORT OVERVIEW
============================================================
...
```

With this patch (8to9):
```
[root@leapp-20240719142203 ~]# /root/tmp_leapp_py3/leapp3 rerun FirstBoot

==> Processing phase `FirstBoot`
====> * enable_rhsm_target_repos
        On the upgraded target system, set release and enable repositories that were used during the upgrade
====> * satellite_upgrader
        Execute installer in the freshly booted system, to finalize Satellite configuration
====> * insights_auto_register
        Automatically registers system into Red Hat Insights
====> * remove_systemd_resume_service
        Remove systemd service to launch Leapp.

Debug output written to /var/log/leapp/leapp-upgrade.log

============================================================
                      REPORT OVERVIEW
============================================================
...
```

LGTM, but waiting for the rebase and test results

**Comment by Rezney** [comment]
The currently failing tests passed in the previous run (no change pushed since) and the time-outing AWS tests are not relevant to this change. Merging.

**Pull request merged**
