### PR TITLE
Bump version to 0.11.0

### PR DESCRIPTION
**Pull request by ZhukovGreen**
## Packaging
- Bump leapp-framework capability to 1.3

### Fixes
- Preserve verbose/debug options during the whole upgrade workflow (#625)
- Print the informative error block to the STDOUT instead of STDERR (#623)

### Enhancements
- Added new reporting tags: `PUBLIC_CLOUD` and `RHUI` (#650)
- Added the possibility to skip actor discovery to improve performance of tests when an actor context is injected directly (#638)
- Introduced the `deprecated` and `suppress_deprecation` decorators to support the deprecation process (#640, #653)
- Store dialog answers in the leapp.db (#651)

### Known issues
- The `suppress_deprecation` decorator causes a traceback in certain cases

### Enhancements
- Updated and improved man pages (#633)

### Fixes
- Raising a missing exception with tests failing under py3 (#647)

### Enhancements
- Added the --actor-config option to `snactor run` to specify a workflow configuration model that should be consumed by actors (#627)

### Enhancements
- The `call` function has been improved to be working on MacOS (#634)

### CODE REVIEW

**Comment by ZhukovGreen** [comment]
@oamg/developers @oamg/qe hi all, please help me to make this list of changes comprehensive. Thank you

**Comment by ZhukovGreen** [comment]
ref https://github.com/oamg/leapp-repository/pull/558

**Comment by pirat89** [comment]
@ZhukovGreen Leapp has different structure for changelogs than leapp-repository.

**Comment by pirat89** [comment]
To preserve original research from @ZhukovGreen , it could be used to complete references to PRs (nice to have):
------------------
# Unsorted // should go in some following chapters or removed

#634 
#635
#633
#641 
#645
#650

# Packaging

# Fixes

* #625 debug mode was inconsistent before. This is now fixed
* #632 empty answerfile when running leapp upgrade fixed
* #647 fixed lost traceback when failing tests running under py3 

# Enhancements

* #627 added support for specifying a model which the actor should consume for configuration data
* #633 man pages updated and improved
* #637 single contributors landing page is introduced
* #640 introduced deprecation functionality to support deprecation process #653
* #648 now tests might be executed without the need to be root



# Additional changes interesting for devels

**Comment by pirat89** [comment]
@oamg/developers  @vinzenz I am just thinking, is there any incompatibility in comparison to previous version? Are we going with `0.11.0` or `0.10.1`? It's just nitpick, we can go with `0.11.0` anyway, but if have still published somewhere doc about our versioning, we should follow it. But I guess we lost it.

@vinzenz If you have time, please create an issue for the decorator we discussed on Monday. Or draft PR, even without tests, just as reference.

**Comment by pirat89** [comment]
@ZhukovGreen actually, template for changelogs could be worthy :)

**Comment by pirat89** [comment]
Empty section should be dropped in the official changelog.

**Comment by pirat89** [comment]
Just hint for changelofs: Things that are not part of packages, should not be usually part of release notes.
It's not 'final' golden rule, but in the most cases it works. 

E.g. Changes in the upstream documentation are not part of the release. As well, documentation is active all the time and it is not versioned till this day. Man page documentation is different, as it is delivered to customers.

OTOH, if something is part of changelogs and we have good documentation for it, link could be worthy.

**Pull request merged**
