### PR TITLE
Unify leapp-preupgrade and leapp-upgrade logs

### PR DESCRIPTION
**Pull request by fernflower**
Instead of having a dedicated leapp-CMDNAME file for
each command log latest run as leapp.log.

### CODE REVIEW

**Comment by vinzenz** [comment]
Well if you would do this now, this would mean you would have to update all the documentation. Also would this clash a bit with C2R - While I am pretty sure why you think we need this, I think there might be an alternative solution. I think it might work if you would set leapp.logger._logger to None after you're done.

**Comment by fernflower** [comment]
Well iiuc clash with convert2rhel is not something we have to worry about anymore, as they won't be using leapp for conversions.
If we don't have doc freeze I'd rather have 1 log file, but maybe `leapp.log` is a very bad name yeah. How about keeping `leapp-upgrade.log` for both preupgrade and upgrade? Or maybe just `leapp-run.log`?

**Comment by fernflower** [comment]
This one came in pair with https://github.com/oamg/leapp-repository/pull/850 which is now closed in favor of https://github.com/oamg/leapp/pull/764

**Pull request closed without merging**
