### PR TITLE
Necessary fixes to make linter happy again

### PR DESCRIPTION
**Pull request by fernflower**
Because unit tests in upstream were not enabled for some
time the following technical debt accumulated.
This patch takes care of make lint command only, not the
unit tests.

Related: OAMG-6723

### CODE REVIEW

**Review by vinzenz — APPROVED** [review]

**Comment by vinzenz** [comment]
LGTM

**Comment by fernflower** [comment]
@vinzenz Squashed the commits. Could you please approve one more time?

**Pull request merged**
