### PR TITLE
Dialog creation fails for a Component without choices

### PR DESCRIPTION
**Pull request by ygalblum**
`choices` is not an attribute of `Component` only of some of its subclasses

### CODE REVIEW

**Comment by ygalblum** [comment]
review please @oamg/developers

**Comment by pirat89** [comment]
@ygalblum  thank you for the contribution! can you elaborate more on problems that the previous solution created? I mean, regarding the code it seems you hit some tracebacks, but I am curious what was the trigger actually as we haven't seen any so far. 

@fernflower  can you take a look?

**Comment by ygalblum** [comment]
> can you elaborate more on problems that the previous solution created?

You can see the dialog I created here: https://github.com/ygalblum/leapp-supplements/blob/veritas-infoscale/repos/system_upgrade_supplements/el7toel8/actors/veritasinstallerpathfinder/actor.py#L19

Since `TextComponent` does not have a `choices` attribute, the code crashes in the line of my fix.

From a quick search I did, I couldn't find any actors that use the `TextComponent` and I guess it was missed in the tests.

**Comment by fernflower** [comment]
Yeah, this very well might be the case as we are not using TextComponents. Could you please cover the failure with a unit test? It would really give us some peace of mind :)

**Comment by ygalblum** [comment]
> Could you please cover the failure with a unit test?

Please see the second commit

**Review by fernflower — APPROVED** [review]
lgtm, thank you for the contribution! 
Scheduling regression tests

**Pull request merged**
