### PR TITLE
Switch to the official composite action for tft

### PR DESCRIPTION
**Pull request by fernflower**
Looks like phracek's github action is mature enough
https://github.com/sclorg/testing-farm-as-github-action

OAMG-6493

### CODE REVIEW

**Comment by fernflower** [comment]
Proof it works - https://github.com/fernflower/leapp/actions/runs/1831938974

**Comment by fernflower** [comment]
After recent changes in github action got 
```
Unexpected input(s) 'tmt_repository', 'test_fmf_plan', 'test_artifacts', valid inputs are ['api_url', 'api_key', 'git_url', 'git_ref', 'github_token', 'tmt_plan_regex', 'compose', 'create_issue_comment', 'pull_request_status_name', 'variables', 'secrets', 'debug', 'update_pull_request_status', 'arch', 'copr', 'copr_artifacts', 'tmt_context', 'artifacts_url']
```
Will fix in next commit

**Review by pirat89 — APPROVED** [review]

**Pull request merged**
