### PR TITLE
Guard the __builtin__.open function before mock

### PR DESCRIPTION
**Pull request by pirat89**
When the \_\_builtin\_\_.open function is mocked inside a unit test, test will fail because the environment cannot be initialised correctly. Problem happens when the os.fdopenfcuntion is called to create file object for the given stdin FD.

This is hackish workround, which stores the original function object during an import of the actor_definition module and ensure this one is be temporary restored when os.fdopen is called.

There should be definitely better solution, so feel free to close unmerged once you find/create better one.

Issue #336

### CODE REVIEW

**Comment by pirat89** [comment]
Provided solution is compatible with Python2 only. As I hope this solution will not be used in the end, I will keep it as it is for now, otherwise it will require change to be compatible with Python 3.

**Comment by vojtechsokol** [comment]
Could you please merge latest changes from master to be able to use the *copr_build* target from the Makefile?

**Comment by vinzenz** [comment]
I guess we will be abandoning this one, I am not really in favour of this since it interferes with the functionality of the framework.

**Comment by pirat89** [comment]
@vinzenz Yeah, I think we agreed we are not able to mock everything and the deal is we will run all tests in vagrant box - so I would go with it that people have to write the code they will be able to test it or they have to write it in the way they do not want to run them on the host system locally. As this was just proposal that helped to discuss this problem, I am closing it.

**Pull request closed without merging**
